package persist;

import junit.framework.TestCase;

/**
 * The class <code>DerbyDatabaseTest</code> contains tests for the class {@link
 * <code>DerbyDatabase</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 4/15/16 4:08 PM
 *
 * @author carasperbeck
 *
 * @version $Revision$
 */
public class DerbyDatabaseTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public DerbyDatabaseTest(String name) {
		super(name);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = persist
 * package.sourceFolder = Whiteboard/src
 * superclassType = junit.framework.TestCase
 * testCase = DerbyDatabaseTest
 * testClassType = DerbyDatabase
 */